"""
Summary Reporter Module

Generates human-readable summaries and PR-ready descriptions.
Enhanced with precision debugging data when available.
"""

import json
from typing import Any


async def generate_summary(state: dict[str, Any]) -> dict[str, Any]:
    """Generate a comprehensive fix summary with precision evidence."""
    failure_title = state.get("failure_title", "Unknown failure")
    failure_type = state.get("failure_type", "unknown")
    root_cause = state.get("root_cause", "Unknown")
    patch = state.get("patch", {})
    validation = state.get("validation", {})
    confidence = state.get("confidence", 0.0)
    reasoning_trace = state.get("reasoning_trace", "")

    # Precision data (may be absent for older/simpler runs)
    evidence_report = state.get("evidence_report", {})
    triage = state.get("triage", {})

    file_path = patch.get("file_path", "unknown")
    explanation = patch.get("explanation", "No explanation available")

    tests_passed = validation.get("tests_passed", 0)
    tests_total = validation.get("tests_total", 0)
    val_status = validation.get("status", "unknown")

    # Extract precision fields
    triage_verdict = evidence_report.get("triage_verdict", triage.get("triage_verdict", ""))
    confidence_calibrated = evidence_report.get("confidence", confidence)
    reproducibility = evidence_report.get("reproducibility", triage.get("reproducibility", ""))
    flake_score = evidence_report.get("flake_score", triage.get("flake_score", 0.0))
    severity = evidence_report.get("severity", "")
    commit_trace = evidence_report.get("commit_trace", triage.get("commit_trace", {}))
    why_real = evidence_report.get("why_real", [])
    why_noise = evidence_report.get("why_noise", [])
    next_action = evidence_report.get("next_action", "")
    signal_quality = evidence_report.get("signal_quality", triage.get("signal_quality", ""))
    evidence_score = evidence_report.get("evidence_score", triage.get("evidence_score", 0.0))

    # PR title
    pr_title = f"fix: {failure_title}"
    if len(pr_title) > 72:
        pr_title = pr_title[:69] + "..."

    # PR body — enhanced with precision data
    pr_body_parts = [
        "## Summary\n",
        f"AutoMerge automatically detected and fixed a {failure_type} issue.\n",
        "### Root Cause\n",
        f"{root_cause}\n",
        "### Changes Made\n",
        f"**File:** `{file_path}`\n",
        f"{explanation}\n",
        "### Validation\n",
        f"- **Status:** {val_status.upper()}",
        f"- **Tests:** {tests_passed}/{tests_total} passed",
        f"- **Confidence:** {confidence_calibrated:.0%}",
    ]

    # Add precision section if available
    if triage_verdict:
        pr_body_parts.extend([
            "",
            "### Debugging Evidence\n",
            f"- **Verdict:** {triage_verdict.replace('_', ' ').title()}",
            f"- **Signal Quality:** {signal_quality.title() if signal_quality else 'N/A'}",
            f"- **Severity:** {severity.title() if severity else 'N/A'}",
            f"- **Reproducibility:** {reproducibility.replace('_', ' ').title() if reproducibility else 'N/A'}",
            f"- **Flake Score:** {flake_score:.0%}" if flake_score > 0 else "",
            f"- **Evidence Score:** {evidence_score:.0%}" if evidence_score > 0 else "",
        ])

        if commit_trace and commit_trace.get("available"):
            suspect = commit_trace.get("suspect_commit", "")
            pr_body_parts.append(
                f"- **Suspect Commit:** `{suspect[:8]}`" if suspect else ""
            )
            pr_body_parts.append(
                f"- **Trace Method:** {commit_trace.get('trace_method', 'N/A')}"
            )

        if why_real:
            pr_body_parts.append("\n**Why this is real:**")
            for reason in why_real:
                pr_body_parts.append(f"- {reason}")

        if next_action:
            pr_body_parts.append(f"\n**Next action:** {next_action}")

    pr_body_parts.extend([
        "",
        "### Agent Reasoning\n",
        "```",
        reasoning_trace,
        "```",
        "",
        "---",
        "*This fix was generated by AutoMerge — autonomous debugging agent.*",
    ])

    pr_body = "\n".join([p for p in pr_body_parts if p is not None])

    impact = "Low risk" if confidence_calibrated > 0.8 else "Medium risk — review recommended"
    if triage_verdict == "noise":
        impact = "Low priority — likely noise"
    elif triage_verdict == "likely_flaky":
        impact = "Flaky — verify stability before merge"

    state["summary"] = {
        # Existing fields (preserved)
        "title": failure_title,
        "root_cause": root_cause,
        "fix_description": explanation,
        "pr_title": pr_title,
        "pr_body": pr_body,
        "reasoning_trace": reasoning_trace,
        "impact_assessment": impact,

        # New precision fields (additive)
        "evidence_report_json": json.dumps(evidence_report, default=str) if evidence_report else "{}",
        "triage_verdict": triage_verdict,
        "confidence_calibrated": round(confidence_calibrated, 3),
        "reproducibility": reproducibility,
        "flake_score": round(flake_score, 3),
        "severity": severity,
        "commit_trace_json": json.dumps(commit_trace, default=str) if commit_trace else "{}",
        "why_real": json.dumps(why_real) if why_real else "[]",
        "why_noise": json.dumps(why_noise) if why_noise else "[]",
        "next_action": next_action,
    }

    return state
